[package]
name = "appcui_proc_macro"
version = "0.1.0"
edition = "2021"
authors = ["gavrilut.dragos@gmail.com"]
description = "..."
license = "MIT"
#repository = ""
#readme = "README.md"

[lib]
proc-macro = true

[dependencies]

[lints]
workspace = true