[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
appcui = { version = "1.0.0", path = "../appcui" }
AppCUIProcMacro = { version = "1.0.0", path = "../appcui-proc-macro"}


[[example]]
name = "test"
path = "test.rs"



[[example]]
name = "buttons"
path = "buttons/main.rs"

[[example]]
name = "canvas"
path = "canvas/main.rs"

[[example]]
name = "checkboxes"
path = "checkboxes/main.rs"

[[example]]
name = "radioboxes"
path = "radioboxes/main.rs"

[[example]]
name = "colorpicker"
path = "colorpicker/main.rs"

[[example]]
name = "hello_world"
path = "hello_world/main.rs"

[[example]]
name = "window_toolbar"
path = "window_toolbar/main.rs"

[[example]]
name = "modal_window"
path = "modal_window/main.rs"

[[example]]
name = "change_menu_status"
path = "change_menu_status/main.rs"

[[example]]
name = "multiple_menus"
path = "multiple_menus/main.rs"

[[example]]
name = "popup_menu"
path = "popup_menu/main.rs"

[[example]]
name = "menus"
path = "menus/main.rs"

[[example]]
name = "password"
path = "password/main.rs"