[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
appcui = { version = "1.0.0", path = "../appcui" }
AppCUIProcMacro = { version = "1.0.0", path = "../appcui-proc-macro"} 

[[example]]
name = "simple_window"
path = "simple_window.rs"

[[example]]
name = "hello_world"
path = "hello_world.rs"