name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test -- --test-threads=1 | tee test-output.txt
        grep -oP 'test result: \K[0-9]+' test-output.txt > test-count.txt
    #- name: Clippy
    #  run: cargo clippy --verbose -- -D warnings
    - name: Audit
      run: cargo audit
    - name: Upload test count
      uses: actions/upload-artifact@v2
      with:
        name: test-count
        path: test-count.txt

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test -- --test-threads=1 | tee test-output.txt
        grep -oP 'test result: \K[0-9]+' test-output.txt > test-count.txt
    #- name: Clippy
    #  run: cargo clippy --verbose -- -D warnings
    - name: Audit
      run: cargo audit
    - name: Upload test count
      uses: actions/upload-artifact@v2
      with:
        name: test-count
        path: test-count.txt
